# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MIT

language: go

go:
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - tip

script:
    - go test

matrix:
    allow_failures:
        - go: tip
